# Feature pyramid networks
# Paper: https://arxiv.org/abs/1612.03144
model:
  class: segmentation_models_pytorch.FPN
  params:
    encoder_name: "resnet34"
    encoder_depth: 5
    encoder_weights: "imagenet"
    decoder_pyramid_channels: 256
    decoder_segmentation_channels: 128
    decoder_merge_policy: "add"
    decoder_dropout: 0.2
    in_channels: 3
    classes: 1
    activation: NULL
    upsampling: 4
    aux_params: NULL
