# LinkNet
# Paper: https://arxiv.org/abs/1707.03718
model:
  name: linknet
  class: segmentation_models_pytorch.Linknet
  params:
    encoder_name: 'resnet101'
    encoder_depth: 5
    encoder_weights: NULL
    decoder_use_batchnorm: True
    in_channels: 3
    classes: 1
    activation: NULL
    aux_params: NULL
