# Pyramid Attention Network
# Paper: https://arxiv.org/abs/1805.10180
model:
  class: segmentation_models_pytorch.PAN
  params:
    encoder_name: "resnet34"
    encoder_weights: "imagenet"
    encoder_dilation: True
    decoder_channels: 32
    in_channels: 3
    classes: 1
    activation: NULL
    upsampling: 4
    aux_params: NULL
