# Pyramid scene parsing network
# Paper: https://arxiv.org/abs/1612.01105
model:
  class: segmentation_models_pytorch.PSPNet
  params:
    encoder_name: "resnet50"
    encoder_weights: NULL
    encoder_depth: 3
    psp_out_channels: 512
    psp_use_batchnorm: True
    psp_dropout: 0.2
    in_channels: 3
    classes: 1
    activation: NULL
    upsampling: 8
    aux_params: NULL
