model:
  name: unet
  class: segmentation_models_pytorch.Unet
  params:
    encoder_name: "densenet121"
    encoder_depth: 5
    encoder_weights: "imagenet"
    decoder_use_batchnorm: True
    # decoder_channels: [256, 128, 64, 32, 16]
    decoder_attention_type: NULL
    # softmax2d => nn.Softmax(dim=1, **params)
    activation: NULL
    in_channels: 3
    classes: 1
