model:
  class: segmentation_models_pytorch.Unet
  params:
    encoder_name: "resnet34"
    encoder_depth: 5
    encoder_weights: "imagenet"
    decoder_use_batchnorm: True
    # decoder_channels: [256, 128, 64, 32, 16]
    decoder_attention_type: NULL
    # nn.Softmax(dim=1, **params)
    activation: softmax2d
    in_channels: 3
    classes: 1
