name: histovision-env
dependencies:
  - python=3.6
  - pytorch=1.1
  - cudatoolkit=10.0
  - numpy
  - matplotlib
  - opencv-python
  - Pip:
      - segmentation-models-pytorch
      - hydra-core
      - albumentations
