criterion:
  name: cross_entropy
  class: histovision.losses.cross_entropy.CrossEntropyLoss
  params:
    weight: NULL
    # Deprecated in favor of reduction
    size_average: NULL
    ignore_index: -100
    reduce: NULL
    reduction: mean
