# Histovision version
version: 0.1.0
# Don't create checkpoint files
debugging: True

defaults:
  # Custom logging
  - hydra/job_logging: custom
  - hydra/hydra_logging: default
  # Custom output for --help
  - hydra/help: custom

dataset: ???  # Specify at runtime
model: ???    # Specify at runtime
criterion:
  class: histovision.losses.MixedLoss
  params:
    alpha: 9.0
    gamma: 1.0
optimizer: Adam
scheduler: ReduceLROnPlateau
# TODO Read provider & trainer from config
provider: histovision.datasets.segdataset.provider
trainer: histovision.trainers.BinaryTrainer

hyperparams:
  batch_size: {train: 32, val: 32}
  lr: 3e-4

dataloader:
  num_workers: 4
  pin_memory: True
  shuffle: True

training:
  start_epoch: 1
  num_epochs: 100
  val_freq: 4
  early_stop:
    patience: 6
  cudnn_benchmark: true

device: cuda

scores: [loss, iou, dice, acc, prec]

augmentations:
  train:
    common:
      ShiftScaleRotate:
        shift_limit: 0
        scale_limit: 0
        rotate_limit: 15
        p: 0.5
      Flip:
        p: 0.5
      RandomRotate90:
        p: 0.5
      RandomBrightnessContrast:
        p: 0.5
      ElasticTransform:
        p: 0.5
      RandomSizedCrop:
        min_max_height: [256, 256]
        height: ${dataset.image_size}
        width: ${dataset.image_size}
        w2h_ratio: 1.0
        interpolation: 1 # cv2.INTER_LINEAR
        p: 1.0

    img_only:
      Normalize:
        mean: [0.0, 0.0, 0.0]
        std: [1.0, 1.0, 1.0]
        always_apply: true

    mask_only:

    final:
      ToTensorV2:

  val:
    common:
      RandomSizedCrop:
        min_max_height: [256, 256]
        height: ${dataset.image_size}
        width: ${dataset.image_size}
        w2h_ratio: 1.0
        interpolation: 1 # cv2.INTER_LINEAR
        p: 1.0

    img_only:
      Normalize:
        mean: [0.0, 0.0, 0.0]
        std: [1.0, 1.0, 1.0]
        always_apply: true

    mask_only:

    final:
      ToTensorV2:

final_weights_path: checkpoints/final_weights.pth
best_weights_path: checkpoints/best_weights.pth
