model: unet
criterion: MixedLoss
optimizer: Adam

hyperparams:
  batch_size: {train: 32, val: 32}
  lr: 3e-4
  num_epochs: 100

scores: [loss, iou, dice, acc, prec]

dataset: MoNuSeg_nitk

augmentations:
  common:
    train:
      ShiftScaleRotate: {shift_limit: 0, scale_limit: 0, rotate_limit: 15, p: 0.5}
      Flip: {p: 0.5}
      RandomRotate90: {p: 0.5}
      RandomBrightnessContrast: {p: 0.5}
      ElasticTransform: {p: 0.5}
      MultiplicativeNoise: {p: 0.5}

    RandomSizedCrop:
      min_max_height:
        - ${dataset.image_size}
        - ${dataset.image_size}
      height: ${dataset.image_size}
      width: ${dataset.image_size}
      w2h_ratio: 1.0
      interpolation: cv2.INTER_LINEAR
      p: 1.0

  image_only:
    Normalize:
      mean: [0.0, 0.0, 0.0]
      std: [1.0, 1.0, 1.0]
      always_apply: true

  # TODO Replace with class_dict
  mask_only:
    Normalize:
      mean: 0.0
      std: 1.0
      always_apply: true

  final:
    - ToTensorV2


start_epoch: 0
num_workers: 4
pin_memory: True
shuffle: True
val_freq: 4
device: cuda
final_weights_path: /Users/Russel/myProjects/histovision/checkpoints/final_weights.pth
best_weights_path: /Users/Russel/myProjects/histovision/checkpoints/best_weights.pth

cudnn_benchmark: true
