dataset:
  name: liver_nitk 
  root: ../../../histovision/data/liver/
  image_dir: "data"
  mask_dir: "bin_l"
  image_glob: "*.png"
  image_size: 256
  class_dict:
    "0": 0
    "255": 1
  in_channels: 3
  num_classes: 2
