dataset:
  name: MoNuSeg
  root: ../../../histovision/data/MoNuSeg/
  image_dir: "imgs"
  mask_dir: "masks"
  image_glob: "*.png"
  image_size: 256
  class_dict:
    "0": 0
    "255": 1
  in_channels: 3
  num_classes: 2
  stats:
    mean: [151.22791557, 110.02420723, 161.24369357]
    std: [47.22264384, 57.9214142, 58.9318906]
