dataset:
  name: MoNuSeg
  root: ../../../histovision/data/MoNuSeg/
  image_dir: "imgs"
  mask_dir: "masks"
  image_glob: "*.png"
  image_size: 256
  class_dict:
    "0": 0
    "255": 1
  in_channels: 3
  num_classes: 2
  stats:
    mean: [0.59305065, 0.43146748, 0.63232821]
    std: [0.18518684, 0.2271428 , 0.23110545]
