dataset:
  name: MoNuSeg_nitk
  root: /Users/Russel/myProjects/histovision/histovision/datasets/MoNuSeg_nitk/
  image_glob: "*.png"
  image_size: 256
  class_dict:
    "0": 0
    "1": 255
  in_channels: 3
  num_classes: 2
