dataset:
  name: MoNuSeg
  root: ../../../histovision/data/MoNuSeg/
  image_dir: "imgs"
  mask_dir: "masks"
  image_glob: "*.png"
  image_size: 256
  class_dict:
    "0": 0
    "255": 1
  in_channels: 3
  num_classes: 2
